# Generated by Django 3.2.15 on 2022-12-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Company_name', models.CharField(max_length=20)),
                ('Email_name', models.CharField(max_length=20)),
                ('Subject_name', models.CharField(max_length=20)),
                ('Password_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Adress_name', models.TextField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
